const express=require('express')
const {getSalePOSs,addSalePOS, deleteSale, updateSale, getSaleById} = require("../controllers/saleposController")
const router = express.Router()
const {protect} = require("../middleware/auth")
router.get("/",protect,getSalePOSs)
router.post("/",protect,addSalePOS)
router.delete("/:id",protect,deleteSale)
router.put("/:id",protect,updateSale)
router.get("/:id",protect,getSaleById)
module.exports=router